### ISSUE TITLE
macOS Big Sur show error: "identity of the developer cannot be confirmed"

### ISSUE THREAD

**Issue by li986390329** [karaggeorge/mac-screen-capture-permissions#5] opened 2020-12-22 12:56 UTC
Question: I use it in my application, everything works fine on Mac OS 10.x.x. but when I use Mac OS 11, the Launcah application will appear "identity of the developer cannot be confirmed".  If I remove this dependency, Then this error will disappear. So please help me, I don't know what went wrong, thank you.

System: macOS Big Sur 11.0.1
node: 12

**Comment by BertholetDamien** [comment] 2021-01-12 23:38
Hi!

I have the exact same problem. It's because this plugin use an external lib. Here the error you can see after investigation:
_message: File /Applications/Berrycast.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions failed on rPathCmd /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (rpath resolved to: (path not found), bundleURL: /Applications/Berrycast.app)_

But I just found that api from electron 8.0+ that allow you to do the check of the permission directly with electron:
[https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos)

I will remove that plugin and remove that Gatekeeper warning =)

Hope that's help!

**Comment by li986390329** [comment] 2021-01-15 09:31
@BertholetDamien Thanks, I have removed this plugin.

**Comment by Lazare-42** [comment] 2021-02-17 09:27
I have faced the same problem but still need this library. You can solve this issue by running the following command on the binary:
`
install_name_tool -delete_rpath /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx ./node_modules/mac-screen-capture-permissions/screen-capture-permissions`

**Comment by Lazare-42** [comment] 2021-02-17 12:42
If you run 
 
`otool -l ./node_modules/mac-screen-capture-permissions/screen-capture-permissions`

You'll notice that the culprit path 

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx`

is a fallback for 

`/usr/lib/swift`

which all users should have from MacOS 10.13.4 (if I remember correctly).

So this modification shouldn't raise an issue.

**Comment by alexgurr** [comment] 2021-03-15 07:34
Also having this issue ☝️

**Comment by karaggeorge** [comment] 2021-03-15 15:49
Is there any way to fix this from the library side? Or is there no workaround other than the ones mentioned above?

**Comment by csett86** [comment] 2021-03-15 17:50
This is fixed from a library side since #6 and once a release it cut, the issue is also solved in a released version.

**Comment by sirtimid** [comment] 2021-03-30 13:21
@karaggeorge any news on the release?

**Comment by csett86** [comment] 2021-04-01 15:15
Fixed with release v2.0.0 just 1 hour ago. Thank you @karaggeorge

**Comment by BertholetDamien** [comment] 2021-04-02 00:35
Nice to hear that! Thanks for the good work gang.

**Comment by karaggeorge** [comment] 2021-04-02 01:40
Thank you guys for all the awesome work! And sorry again for taking so long with this

**Closed as completed by karaggeorge** 2021-04-02 01:40 UTC
